# Generated by Django 4.1.2 on 2022-10-31 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haunted_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="api_key", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
