# Generated by Django 4.1.3 on 2022-11-23 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("haunted_auth", "0002_alter_apikey_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"get_latest_by": "created_at", "ordering": ("created_at",)},
        ),
    ]
