# Generated by Django 4.1.2 on 2022-10-31 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haunted_auth", "0002_alter_apikey_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="owner",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
