# Generated by Django 4.1.3 on 2022-11-29 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_levels(apps, schema_editor):
    Gameflow = apps.get_model("ghost_sharing", "Gameflow")
    Level = apps.get_model("ghost_sharing", "Level")
    Ghost = apps.get_model("ghost_sharing", "Ghost")
    db_alias = schema_editor.connection.alias
    unknown_gameflow = Gameflow.objects.create(
        identifier="unknown",
        title="unknown",
    )
    for ghost in Ghost.objects.using(db_alias).all():
        ghost.level_new, _ = Level.objects.get_or_create(
            gameflow=unknown_gameflow,
            identifier=ghost.level,
            title=ghost.level,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ghost_sharing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gameflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("identifier", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ("created_at",),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("identifier", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=128)),
                (
                    "gameflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="levels", to="ghost_sharing.gameflow"
                    ),
                ),
            ],
            options={
                "unique_together": {("gameflow", "identifier")},
            },
        ),
        migrations.AddField(
            model_name="ghost",
            name="level_new",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ghosts", to="ghost_sharing.level"
            ),
        ),
        migrations.RunPython(
            code=migrate_levels,
            reverse_code=None,
            atomic=True,
        ),
    ]
