# Generated by Django 4.1.3 on 2022-11-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghost_sharing", "0002_gameflow_level_ghost_level_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ghost",
            name="level",
        ),
        migrations.RenameField(
            model_name="ghost",
            old_name="level_new",
            new_name="level",
        ),
        migrations.AlterField(
            model_name="ghost",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="ghosts", to="ghost_sharing.level"
            ),
        ),
    ]
