# Generated by Django 4.1.3 on 2022-11-01 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("message", models.TextField()),
                (
                    "background_color",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("success", "Success"),
                            ("danger", "Danger"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="light",
                        max_length=16,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(choices=[("white", "White"), ("black", "Black")], default="black", max_length=16),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
