# Generated by Django 4.1.3 on 2022-11-21 21:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteapi", "0002_alter_announcement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="message",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
