# Generated by Django 4.1.3 on 2022-11-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteapi", "0002_alter_announcement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="message",
            field=models.TextField(blank=False, null=False),
        ),
    ]
