# Generated by Django 4.1.2 on 2022-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="description",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
