# Generated by Django 4.1.3 on 2022-11-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_sessions", "0002_session_players"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
    ]
