# Generated by Django 4.1.3 on 2022-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haunted_sessions", "0003_alter_session_options_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="end",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="is_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="start",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
