# Generated by Django 4.1.3 on 2022-11-23 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("haunted_sessions", "0004_session_end_session_is_event_session_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"get_latest_by": "created_at", "ordering": ("created_at",)},
        ),
    ]
