# Generated by Django 4.1.3 on 2022-12-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_sessions", "0006_remove_session_is_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="private",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
