# Generated by Django 4.1.3 on 2022-12-02 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_sessions", "0007_session_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="last_used",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
