"""
Django settings for hauntedserver project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# FIXME SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f4_z*xoe#1lnd75fs@v$st$n*%cu&+2yghc8wq6%5rrhijmd(0"

# FIXME SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "corsheaders",
    "siteapi",
    "haunted_auth",
    "haunted_sessions",
    "django_email_verification",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hauntedserver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "hauntedserver.jinja2.environment",
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hauntedserver.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


def verified_callback(user):
    user.is_active = True


EMAIL_VERIFIED_CALLBACK = verified_callback

EMAIL_MAIL_HTML = "email_confirmation_body.html.j2"
EMAIL_MAIL_PLAIN = "email_confirmation_body.txt.j2"
EMAIL_MAIL_SUBJECT = "Confirm your email"
EMAIL_MAIL_PAGE_TEMPLATE = "confirm_template.html"
EMAIL_MAIL_TOKEN_LIFE = 60 * 60

if DEBUG:
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOWED_ORIGINS = ("http://localhost:8080", "http://127.0.0.1:8080")
    CSRF_TRUSTED_ORIGINS = ("http://localhost:8080", "http://127.0.0.1:8080")
    ALLOWED_HOSTS = ("localhost", "127.0.0.1")

    EMAIL_FROM_ADDRESS = "noreply@example.com"
    EMAIL_PAGE_DOMAIN = "https://example.com/"

    # For Django Email Backend
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST = "smtp.example.com"
    EMAIL_PORT = 587
    EMAIL_HOST_USER = "example@example.com"
    EMAIL_HOST_PASSWORD = ""
    EMAIL_USE_TLS = True
else:
    EMAIL_FROM_ADDRESS = "noreply@example.com"
    EMAIL_PAGE_DOMAIN = "https://example.com/"

    # For Django Email Backend
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_HOST_USER = "mymail@gmail.com"
    EMAIL_HOST_PASSWORD = "mYC00lP4ssw0rd"  # os.environ['password_key'] suggested
    EMAIL_USE_TLS = True

SITE_ID = 1
